<#include "variable.ftlh">

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>${Title}</title>
<link rel="stylesheet" href="${RootPath}/layui/css/layui.css?V=${V}" media="all">
<link rel="stylesheet" href="${RootPath}/layuiadmin/style/admin.css?V=${V}" media="all">
<link rel="stylesheet" href="${RootPath}/my/css/layui.css?V=${V}" media="all">
